---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
{{- if .Values.annotations }}
  annotations:
  {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  description: >-
    This Task can be used to run a Maven build.

  workspaces:
    - name: source
      optional: false
      description: The workspace consisting of maven project.

  params:
    - name: GOALS
      description: maven goals to run
      type: array
      default:
        - "package"
    - name: MAVEN_MIRROR_URL
      description: The Maven repository mirror url
      type: string
      default: ""
    - name: SUBDIRECTORY
      type: string
      description: >-
        The subdirectory within the repository for sources on
        which we want to execute maven goals.
      default: "."

  stepTemplate:
    env:
{{- $variables := list
      "params.MAVEN_MIRROR_URL"
      "params.SUBDIRECTORY"
      "workspaces.source.path"
      "workspaces.source.volume"
}}
{{- include "environment" ( list $variables ) | nindent 6 }}

  steps:
{{- include "load_scripts" ( list . "maven-" ) | nindent 4 }}

    - name: maven-generate
      image: {{ .Values.images.minimal }}
      env:
        - name: HOME
          value: /tekton/home
      command:
        - /scripts/maven-generate.sh
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
        - name: maven-settings-dir
          mountPath: /maven-generate

    - name: maven-goals
      env:
        - name: HOME
          value: /tekton/home
      image: {{ .Values.images.maven }}
      workingDir: $(workspaces.source.path)/$(params.SUBDIRECTORY)
      command: ["/usr/bin/mvn"]
      args:
        - -s
        - maven-generate/settings.xml
        - "$(params.GOALS[*])"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: maven-settings-dir
          mountPath: /maven-generate

  volumes:
    - name: scripts-dir
      emptyDir: {}
    - name: maven-settings-dir
      emptyDir: {}