---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: maven
  labels:
    app.kubernetes.io/version: {{ .Chart.Version }}
{{- if .Values.annotations }}
  annotations:
  {{- .Values.annotations | toYaml | nindent 4 }}
{{- end }}
spec:
  description: >-
    This Task can be used to run a Maven build.

  workspaces:
    - name: source
      optional: false
      description: The workspace consisting of maven project.
    - name: server_secret
      optional: true
      description: The workspace containing server secrets (username and password)
    - name: proxy_secret
      optional: true
      description: The workspace containing proxy server access credentials (username, password).
    - name: proxy_configmap
      optional: true
      description: The workspace containing some proxy values (proxy_port,proxy_host,proxy_protocol,proxy_non_proxy_hosts)
    - name: maven_settings
      optional: true
      description: The workspace consisting of the custom maven settings provided by the user.
  params:
    - name: GOALS
      description: maven goals to run
      type: array
      default:
        - "package"
    - name: MAVEN_MIRROR_URL
      description: The Maven repository mirror url
      type: string
      default: ""
    - name: SUBDIRECTORY
      type: string
      description: >-
        The subdirectory within the repository for sources on
        which we want to execute maven goals.
      default: "."

  stepTemplate:
    env:
{{- $variables := list
      "params.MAVEN_MIRROR_URL"
      "params.SUBDIRECTORY"
      "workspaces.source.path"
      "workspaces.source.bound"
      "workspaces.server_secret.path"
      "workspaces.server_secret.bound"
      "workspaces.proxy_secret.path"
      "workspaces.proxy_secret.bound"
      "workspaces.proxy_configmap.path"
      "workspaces.proxy_configmap.bound"
      "workspaces.maven_settings.path"
      "workspaces.maven_settings.bound"
}}
{{- include "environment" ( list $variables ) | nindent 6 }}

  steps:
    - name: maven-generate
      image: {{ .Values.images.minimal }}
      env:
        - name: HOME
          value: /tekton/home
      script: |
{{- include "load_scripts" ( list . ( list "maven-" ) ( list "/scripts/maven-generate.sh" ) ) | nindent 8 }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: scripts-dir
          mountPath: /scripts
        - name: maven-settings-dir
          mountPath: /maven-generate

    - name: maven-goals
      env:
        - name: HOME
          value: /tekton/home
      image: {{ .Values.images.maven }}
      workingDir: $(workspaces.source.path)/$(params.SUBDIRECTORY)
      command: ["/usr/bin/mvn"]
      args:
        - -s
        - maven-generate/settings.xml
        - "$(params.GOALS[*])"
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
      volumeMounts:
        - name: maven-settings-dir
          mountPath: /maven-generate

  volumes:
    - name: scripts-dir
      emptyDir: {}
    - name: maven-settings-dir
      emptyDir: {}
